### ISSUE TITLE
Macro handling "Vier/Acht Ziele" & "Mehrere Ziele"

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-extensiondb#16]
There are many locations that increase costs with more targets selected. Currently this is only automated for two targets as the cost in straight forward. Creating a macro for this would allow many spells extensions to be automated thus having a big impact on completion with a single macro.
If it is possible to access player selections this should be totally doable, right?
Example:
```
"Atemnot": [
    {
      "name": "Zwei Ziele",
      "complete": true,
      "changes": [
        {"key": "system.AsPCost.value", "mode": 2, "value": 2}
      ]
    },
    {
      "name": "Vier Ziele",
      "complete": false,
      "changes": [
      ]
    },
    {
      "name": "Acht Ziele",
      "complete": false,
      "changes": [
      ]
    }
  ],
```

**Comment by Plushtoast** [comment]
Geht, ich mach ein Beispiel

**Comment by Plushtoast** [comment]
Siehe Atemnot vier Ziele makro

**Comment by Rapunzel77** [comment]
Soll das für jedes Vorkommen angelegt werden? Das sieht aus, als ob sich da auch gut eine Bibliothek machen lässt:
* mutlitarget-2AsP_per_target
* mutlitarget-4AsP_per_target
* ...
Alternative:
* 2targets-2AsP_per_target
* 4targets-2AsP_per_target
* 2targets-4AsP_per_target
* 4targets-4AsP_per_target
Da könnte man dann auch zentral noch nach einer Obergrenze an zielen prüfen oder sonst irgendetwas mit dem Wissen tun wie viele ziele es sein sollten.

Vom Aufwand ist es fast gleich, daher würde ich das machen wie du das für besser hällst. Meinen Fingern kribbelt es bei so-etwas nur es wiederverwendbar zu machen.

**Comment by Plushtoast** [comment]
Ja, da hast du wohl recht. War mir nicht sicher ob man da spaeter noch anderen code hinzufügen will. Aber dann kann man es immer noch aufblasen
