### ISSUE TITLE
new key allowing "Zauberdauer modifizierbar"

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-extensiondb#18]
There are several spell extensions that make cast time modification possible. This is already available for spells as the GUI does not allow modification for Oktagramma but it does for Aquafaxius. Such a modification would make many automation possible though these json files but require (core ?) module changes.

**Comment by Rapunzel77** [comment]
Is this something I could do with `source.system.canChangeCastingTime="true"` ?

**Comment by Plushtoast** [comment]
yes I think you can add that key already and th system will support it later on

**Comment by Plushtoast** [comment]
leave it open

**Comment by Plushtoast** [comment]
ah sollte
```
system.canChangeCastingTime.value 
```
sein
