### ISSUE TITLE
New Key: Spell modification without increasing cast difficulty

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-extensiondb#19]
There are several spells that lift cast difficulty from modifying spells. I assume that this can be automated using a new key to handle it. This can be done manually quite easily so I would but it at a lower ranking.

Example:

```
"Sphärenbann": [
    {
      "name": "Reichweite erhöhen",
      "complete": false,
      "changes": [

      ]
    },
    {
      "name": "Zauberdauer senken",
      "complete": false,
      "changes": [

      ]
    },
    {
      "name": "Kosten senken",
      "complete": false,
      "changes": [

      ]
    }
  ],
```

**Comment by Plushtoast** [comment]
related https://github.com/Plushtoast/dsa5-foundryVTT/issues/857

**Comment by Plushtoast** [comment]
Die Keys werden ab 4.2.0 existieren.
Hab sie der Übersicht hinzugefügt.
Wär cool falls du dazu kommst, muss dann eh alle Module vermutlich updaten.

**Comment by Rapunzel77** [comment]
Bevor ich alles eintrage hier kurz mein Verständnis:

Sphärenbann - Reichweite Erhöhen:
```{"key": "system.spellRollModifiers.increaseRangeSpell.mod", "mode": 5, "value": "0"}```

Dann entsprechend immer für Zauber/Liturgien/... sowie der Zaubermodifikation entsprechend auswählen.

Richtig?

**Comment by Plushtoast** [comment]
Jo exakt!

**Comment by Rapunzel77** [comment]
closing as things are merged and will be integrated in next release

**Comment by Plushtoast** [comment]
ich öffne das wieder, dass ich mich erinner da noch was tun zu müssen

**Comment by Plushtoast** [comment]
Außerdem gibt es leider so dinge wie:
![grafik](https://user-images.githubusercontent.com/44941845/206681699-110b94a3-7e75-4e04-9f81-f3ad7122a501.png)
