### ISSUE TITLE
Allowing a makro/action to trigger after the spell duration is over

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-extensiondb#20]
There are several spells that have extensions which create an effect after the actual effect expires. An example is "Zwingtanz - Erschöpfender Tanz". It would be great to be able to easily automate these as that is something that could be easily forgotten by the game master or the player in the heat of the game being played.

**Comment by Plushtoast** [comment]
Geht, ich mach ein Beispiel.

**Comment by Plushtoast** [comment]
Der Zwingtanz ist allerdings noch gar nicht automatisiert, falls du noch ein anderes Beispiel hast...

**Comment by Rapunzel77** [comment]
Ein anderes Beispiel ist Höllenpein

**Comment by Plushtoast** [comment]
beispiel fertig
