### ISSUE TITLE
Schlangenruf - Götterwirken2_spells

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-extensiondb#37]
in der json steht 

```
{
  "Schlangenruf": [
    {
      "name": "Blitzschnell",
      "complete": false,
      "changes": [

      ]
    },
    {
      "name": "Angriffslustig",
      "complete": false,
      "changes": [

      ]
    },
    {
      "name": "Giftig",
      "complete": false,
      "changes": [

      ]
    }
  ]
}
```

im Wiki finde ich aber (https://ulisses-regelwiki.de/liturgie.html?liturgie=Schlangenruf)
- Längere Wirkungsdauer 
- Mehr Befehle
- Mehr Wesen

Ist das hier ein anderer Schlangenruf?

**Comment by Plushtoast** [comment]
Gibt das als liturgie und zauber:
https://ulisses-regelwiki.de/zauber.html?zauber=Schlangenruf

**Comment by Rapunzel77** [comment]
ahh ja - ich hatte bei Götterwirken nicht direkt an zauber gedacht - auch wenn es da steht.
