### ISSUE TITLE
Elementarium

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-extensiondb#39]
Auf den ersten blick sieht es so aus, als ob im Elementarium nur aus den anderen Bänden (Magie I, II, III) Zaubersprüche zusammengestellt wurden. Ist es notwendig die json noch einmal extra zu haben - das ist ja eher ein suchen und kopieren - und dann etwas schwierig konsistent zu halten.

Wenn es hier einzelne Zauber gibt die sonst nicht aufgeführt werden wären diese natürlich sinnvoll - irgendwie scheint es im Wiki
https://ulisses-regelwiki.de/zauberauswahl.html?publikation=*
nicht einmal die Publikation  als Filter zu geben.

**Comment by TarionT** [comment]
Ich denke es gibt deshalb noch keinen Filter, weil die Daten noch nicht eingepflegt wurden in das Regelwiki. Das Elementarium ist noch recht jung.

**Comment by Rapunzel77** [comment]
Ahh stimmt. Ich verschätze mich da immer, wenn ich das schon aus dem collectors club vorher hatte...
Dennoch scheint mir dieses json eine Wiederholung zu sein. Ich vermute es wäre einfacher es aus den anderen zu generieren, dann laufen die Einträge nicht auseinander + eventuell ein paar neue Zauber die hier aufgeführt sein könnten.

**Comment by Plushtoast** [comment]
Wir duplizieren das, weil DSA das so macht und es hier und da feine Unterschiede gibt.

**Comment by Rapunzel77** [comment]
Alles klar - dann machen wir die wohl doch noch einmal 👍

**Comment by Rapunzel77** [comment]
habe die Unterschiede gefunden - ich hoffe ein errata führt das zusammen, ansonsten könne eine gute Automatisierung schwierig werden.
