### ISSUE TITLE
Change Preselected size/shape of area effects

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-extensiondb#53]
There are some extensions that change the shape and dimensions of aoe spells (or make them such). 
Would it be possible to add this as a separate key? Currently I marked all of these as incomplete.

example (Exposami, Feuerwand, ...):  "QS x 20 Schritt" and shape "Sphäre"

**Comment by Plushtoast** [comment]
Sollte schon mit den keys:

system.target.type
system.target.value
system.target.angle
system.target.width

und override gehen. hab ich aber nicht getestet

**Comment by Rapunzel77** [comment]
Ich habe die keys mal in die Tabelle README.md. Die Beispiele und Beschreibung sind sicherlich nichts ganz richtig :)
ist alles in PR #52

**Comment by Plushtoast** [comment]
sehr fleißig wieder

**Comment by Plushtoast** [comment]
readme aktualisiert

**Comment by Rapunzel77** [comment]
Danke - ich habe das mal verwendet und hoffe das passt so.
