### ISSUE TITLE
[Question] Erschaffung

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-extensiondb#55]
Es gibt Zauber die Dinge erschaffen. Dabei meine ich nicht so etwas wie Flammenschwert oder Scharfes Instrument sondern eher in die Richtung von Feenstaub oder Invocatio Minima. Ich habe diese immer als `"complete": false` markiert, da so etwas ja auch als Gegenstand erschaffen werden könnte. Hältst du das für sinnvoll - dann lasse ich es so. Wenn nicht markiere ich die gerne alle als `"complete": true`

**Comment by Plushtoast** [comment]
hälte es nicht viel realistisch solche gegenstände zu erschaffen und es wäre jeweils ein eigenes macro oder so wahrscheinlich
würde die nicht automatisieren also complete: true

**Comment by Rapunzel77** [comment]
alles klar - mache ich dann wenn ich da vorbeikomme
