### ISSUE TITLE
Abweichungen zwischen Büchern

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-extensiondb#61]
Da du sowieso alles einmal parsen musst, um es zu transformieren und wir mit dem Grimorum eine Einheitliche darstellung aller Zauber über alle vorherigen Publikationen bekommen haben wäre es doch bestimmt möglich zu sehen, ob es Abweichungen zwischen den Darstellungen gibt, oder?

Wenn du das automatisieren könntest wäre das super.

(aktuell habe ich das Elementarium nicht angefasst, das hole ich nach)

**Comment by Plushtoast** [comment]
dafür war das "dirty" flag

die abweichung zu vergleichen lohnt sich meines erachtens aber nicht, da man sowieso alles nue lesen muss

**Comment by Rapunzel77** [comment]
Mir war nur aufgefallen, dass es Unterschiede zwischen Necro und Magie 1 (oder so) gab. Auch bevor ich die Sprüche angefasst hatte. Macht aber vielleicht keinen Sinn.

**Comment by Plushtoast** [comment]
Ja aber gilt nur noch grimorum und diviniarium. Alles andere ist wurst.Verschiedene Versionen zu maintainen haben wir aufgegeben das gibt nur Probleme Von meinem iPhone gesendetAm 09.06.2024 um 19:34 schrieb Rapunzel77 ***@***.***>:﻿
Mir war nur aufgefallen, dass es Unterschiede zwischen Necro und Magie 1 (oder so) gab. Auch bevor ich die Sprüche angefasst hatte. Macht aber vielleicht keinen Sinn.

**Comment by Rapunzel77** [comment]
Genau - es ist nur schwierig zu finden wenn ein Spruch in 2-3 Büchern ist (Magie 1, Necro, Elementarium) und bei einem Steht 

```
"name": "Halbkreis",
      "complete": false,
      "changes": [
      ]
```
und in dem anderen

```
"name": "Halbkreis",
      "complete": true,
      "changes": [
        {
          "key": "system.target.type",
          "mode": 5,
          "value": "cone"
        },
        {
          "key": "system.target.angle",
          "mode": 5,
          "value": 180
        }
      ]
```

da ist halt schwierig zu finden
